DROP TABLE IF EXISTS DEVIS, INTERVENTION, EQUIPE, COMMAND ,DEMAND, EMPLOYEE, OFFRE , PLACE;



CREATE TABLE IF NOT EXISTS PLACE(
  ID_PLACE INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
  LATITUDE INT(11) UNIQUE,
  LONGITUDE INT(11) UNIQUE,
  ALTITUDE INT(11),
  PLACE_NAME VARCHAR(26) NOT NULL,
  REMARQUE LONGTEXT
);

CREATE TABLE IF NOT EXISTS USERS(
	ID_USER INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
	USER_NAME TINYTEXT NOT NULL,
	USER_EMAIL TINYTEXT,
	USER_PASSWORD LONGTEXT NOT NULL,
	ADDRESS VARCHAR(20),
	EMPLOYEE_STATUS VARCHAR(26) NOT NULL --SOI UN C ou un G
);

CREATE TABLE IF NOT EXISTS EMPLOYEE(
  ID_EMPLOYEE INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
  EMPLOYEE_NAME VARCHAR(26),
  EMPLOYEE_LAST_NAME VARCHAR(26),
  NUM_SECURITE_SOCIAL VARCHAR(20),
  EMPLOYEE_MAIL TINYTEXT NOT NULL,
  EMPLOYEE_PASSWORD LONGTEXT NOT NULL,
  EMPLOYEE_STATUS VARCHAR(26) NOT NULL
);


CREATE TABLE IF NOT EXISTS OFFRE(
  ID_OFFRE INT(11) AUTO_INCREMENT PRIMARY KEY UNIQUE,
  REFERENCE INT(11),
  LABEL TINYTEXT NOT NULL,
  FILE_NAME TINYTEXT NOT NULL,
  DESCRIPTION LONGTEXT,
  TYPE_OFFRE INT(1),
  QUANTITE INT(11) DEFAULT NULL,
  PRIX int(11)
);

CREATE TABLE IF NOT EXISTS DEMAND (
  ID_DEMAND INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
  DATE_DEMANDE DATE,
  REMARQUE LONGTEXT,
  ID_USER INT(11),
  ID_OFFRE INT(11),
  DATE_START DATE,
  DATE_END DATE,
  ACCEPTED BOOLEAN,
  ID_PLACE INT(11),
  QUANTITE_DEMAND INT(11),
  FOREIGN KEY(ID_OFFRE) REFERENCES OFFRE(ID_OFFRE) ON DELETE CASCADE ,
  FOREIGN KEY(ID_PLACE) REFERENCES PLACE(ID_PLACE) ON DELETE CASCADE,

  FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS COMMAND(
  ID_COMMAND INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
  ID_DEMAND INT(11),
  DATE_COMMAND DATE,
  DATE_VALIDATION DATE,
  DATE_START DATE,
  DATE_END DATE,
  VALIDATE_COMMAND INT(11) DEFAULT NULL,
  PAYMENT INT(11) DEFAULT NULL,
  FOREIGN KEY(ID_DEMAND) REFERENCES DEMAND(ID_DEMAND) ON DELETE CASCADE


);



CREATE TABLE IF NOT EXISTS EQUIPE (
  ID_EQUIPE INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
  NAME_EQUIPE VARCHAR(26),
  DESCRIPTION LONGTEXT,
  CURRENT_LOCATION INT(11),
  NB_MEMBERS INT(11),
  FOREIGN KEY(CURRENT_LOCATION) REFERENCES PLACE(ID_PLACE) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS INTERVENTION(
  ID_INTERVENTION INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
  ID_EQUIPE INT(11) DEFAULT NULL,
  ID_COMMAND INT(11),
  FOREIGN KEY(ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE) ON DELETE CASCADE,
  FOREIGN KEY(ID_COMMAND) REFERENCES COMMAND(ID_COMMAND) ON DELETE CASCADE
);

INSERT IGNORE INTO EMPLOYEE (ID_EMPLOYEE, EMPLOYEE_NAME, EMPLOYEE_LAST_NAME, NUM_SECURITE_SOCIAL, EMPLOYEE_MAIL, EMPLOYEE_PASSWORD, EMPLOYEE_STATUS) VALUES ('1', 'admin', 'admin', '12342', 'root@test.fr', '$2y$10$1BRWR463QzEeV8hbwjfVxOGwcX2N2Tdmi88oscVgM1FrDZTDlfNfG', 'R');
INSERT IGNORE INTO EMPLOYEE (ID_EMPLOYEE, EMPLOYEE_NAME, EMPLOYEE_LAST_NAME, NUM_SECURITE_SOCIAL, EMPLOYEE_MAIL, EMPLOYEE_PASSWORD, EMPLOYEE_STATUS) VALUES ('2', 'com', 'com', '1234', 'com@test.fr', '$2y$10$1BRWR463QzEeV8hbwjfVxOGwcX2N2Tdmi88oscVgM1FrDZTDlfNfG', 'M');
INSERT IGNORE INTO EMPLOYEE (ID_EMPLOYEE, EMPLOYEE_NAME, EMPLOYEE_LAST_NAME, NUM_SECURITE_SOCIAL, EMPLOYEE_MAIL, EMPLOYEE_PASSWORD, EMPLOYEE_STATUS) VALUES ('3', 'ges', 'ges', '1234', 'ges@test.fr', '$2y$10$1BRWR463QzEeV8hbwjfVxOGwcX2N2Tdmi88oscVgM1FrDZTDlfNfG', 'G');

CREATE TABLE  IF NOT EXISTS DEVIS(
  ID_DEVIS_PRODUIT INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
  ID_DEVIS INT(11),
  ID_EMPLOYEE INT(11),
  ID_COMMAND INT(11),
  FOREIGN KEY(ID_EMPLOYEE) REFERENCES EMPLOYEE(ID_EMPLOYEE) ON DELETE CASCADE,
  FOREIGN KEY(ID_COMMAND) REFERENCES COMMAND(ID_COMMAND) ON DELETE CASCADE
);



INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Bi-bouteilles', 'bloc_bi_bouteilles.jpg', 'In the case of scuba diving, the devices used are twin-bottle diving blocks. They are equipped with a bloody and a subcutaneous one.',0,10, '70');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Détendeur', 'détendeur.jpg', 'We provide a surveillance surface boat, suitable for receiving the rescue diver.',0,10, '30');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Gilet stabilisateur', 'stab-solid.jpg', 'Usable from 0 to 12 meters, depending on the HOC. Beyond 12 meters, the wearing of the stabilizer vest is mandatory.',0,10, '60');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Chronomètre', 'chronomètre.jpg', 'Part of the individual equipment, usable on the surface.',0,10, '15');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Profondimètre', 'profondimètre.jpg', 'Part of the individual equipment, usable at a depth of more than 12 metres.',0,10, '15');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Couteau', 'couteau.jpg', 'Part of the individual equipment.',0,10, '10');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Robinetterie', 'robinetterie.jpg', 'Valves are dismantled annually whenever an anomaly is detected.',0,10, '30');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Jeu de tables de plongée immergeable', 'table-de-plongée.jpg', 'Part of the individual equipment, can be used in depth.',0,10, '20');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Masque à verres correcteurs', 'masque-de-plongee-avec-verres-correcteurs-pro.jpg', 'Mask resistant to dives over 12 meters. At the request of the diver or the COH, adaptable according to the physiological criteria.',0,10, '30');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Compresseur', 'compresseur.jpg', 'The compressors must be sucked in in a place where there is no risk of pollution.',0,10, '50');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Pavillon Alpha', 'pavillon-alpha.jpg', 'The use of an Alpha flag indicating the presence of divers, visible from a distance sufficient to ensure the safety of responders, is mandatory.',0,10, '15');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, QUANTITE,PRIX) VALUES ('Trousse d\’urgence', 'trousse-de-secours-plongee.jpg', 'Medical equipment in case of emergency. Each site must have at least one updated and revised medical oxygen inhalation kit and emergency kit.',0,10, '20');

INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, PRIX) VALUES ('Installation de matériel', 'equipement_plongee.jpg', 'We provide the complete installation of our equipment.',1,'100');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, PRIX) VALUES('Maintenance de matériel', 'photo-materiel.jpg', 'Our teams check the condition of the equipment and guarantee its evolution.',1,'100');
INSERT IGNORE INTO OFFRE(LABEL,FILE_NAME, DESCRIPTION,TYPE_OFFRE, PRIX) VALUES ('Support de surface', 'photo-equipement.jpg', 'We provide a surveillance surface boat, suitable for receiving the rescue diver.',1,'100');


INSERT IGNORE INTO DEMAND(DATE_DEMANDE, REMARQUE, ID_USER, ID_OFFRE, DATE_START, DATE_END, ACCEPTED,QUANTITE_DEMAND )  VALUES(CURRENT_DATE ,'Mes voeux', 1,1,CURRENT_DATE ,CURRENT_DATE ,FALSE ,1);

INSERT IGNORE INTO PLACE(LATITUDE, LONGITUDE, ALTITUDE, PLACE_NAME) VALUES (30,30,40,'France');
INSERT IGNORE INTO PLACE(LATITUDE, LONGITUDE, ALTITUDE, PLACE_NAME) VALUES (31,31,40,'Japon')


